# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0003_upvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='category1',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='question',
            name='category2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='category3',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='category4',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
