# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0004_auto_20160222_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='faculty_upvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='category1',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='question',
            name='category2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category4',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
