# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0005_auto_20160302_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
