# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 14:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('QA', '0005_auto_20160302_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customuser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(blank=True, max_length=300, null=True)),
                ('categories', models.ManyToManyField(related_name='intrested_in', to='QA.Categories')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QA.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category1', to='QA.Categories'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category2', to='QA.Categories'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category3', to='QA.Categories'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category4', to='QA.Categories'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QA.Answer'),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='upvoted_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
