# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0006_auto_20160306_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 12, 7, 50, 23, 132779, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
