# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0007_auto_20160303_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category5',
        ),
    ]
