# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0009_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='follow',
            field=models.IntegerField(default=0),
        ),
    ]
