# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0014_auto_20160314_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QA.Customuser'),
        ),
    ]
