# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-19 06:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0016_auto_20160315_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 19, 6, 51, 31, 848721, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
